version: '2'
services:
  web:
    image: gitea/gitea:1.12.4
    volumes:
      - /www/gitea/data:/data
    ports:
      - "3000:3000"
      - "23:22"
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - /www/gitea/db:/var/lib/mysql
